services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env-local
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env-local
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    env_file:
      - .env-local
    depends_on:
      - prometheus
  
  # loki:
  #   image: grafana/loki:latest
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml
  #   volumes:
  #     - ./loki-config.yml:/etc/loki/local-config.yaml

  # promtail:
  #   image: grafana/promtail:latest
  #   volumes:
  #     - ./promtail-config.yml:/etc/promtail/config.yml
  #     - /var/log:/var/log
  #   command: -config.file=/etc/promtail/config.yml -config.expand-env=true

volumes:
  grafana-data:
  