global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "django"
    static_configs:
      - targets: ["app:8000"]
  # - job_name: "prometheus"
  #   #metrics_path: "/metrics/"
  #   static_configs:
  #     - targets: ["localhost:8000"]
  # - job_name: "postgres"
  #   metrics_path: "/metrics/"
  #   static_configs:
  #     - targets: ["db:5432"]